// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CardCategoryList: typeof import('./src/components/Cards/list/CardCategoryList.vue')['default']
    CardDishList: typeof import('./src/components/Cards/list/CardDishList.vue')['default']
    CardEmployeeList: typeof import('./src/components/Cards/list/CardEmployeeList.vue')['default']
    CardMessage: typeof import('./src/components/Cards/CardMessage.vue')['default']
    CardOrdersList: typeof import('./src/components/Cards/list/CardOrdersList.vue')['default']
    CardSetmealList: typeof import('./src/components/Cards/list/CardSetmealList.vue')['default']
    DashboardSidebar: typeof import('./src/components/Sidebars/DashboardSidebar.vue')['default']
    DefaultFooter: typeof import('./src/components/Footers/DefaultFooter.vue')['default']
    DefaultHeader: typeof import('./src/components/Headers/DefaultHeader.vue')['default']
    DrawerForm: typeof import('./src/components/Form/DrawerForm.vue')['default']
    MainFooter: typeof import('./src/components/Footers/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/Headers/MainHeader.vue')['default']
    NewEmployee: typeof import('./src/components/Form/NewEmployee.vue')['default']
    NewSetmealForm: typeof import('./src/components/Form/NewSetmealForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WidgetCounter: typeof import('./src/components/Widgets/WidgetCounter.vue')['default']
    WidgetSalary: typeof import('./src/components/Widgets/WidgetSalary.vue')['default']
  }
}
