server.port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/db
        username: root
        password: 123456
    thymeleaf:
        cache: false
    main:
        banner-mode: off
    data:
        redis:
            host: localhost
            port: 6379
            database: 0
            timeout: 5000
            password: 123456
            jedis:
                pool:
                    max-active: 8
                    max-wait: 1ms
                    max-idle: 4
                    min-idle: 0
    cache:
        redis:
            time-to-live: 1800000
#    jackson:
#        default-property-inclusion: non_null
mybatis:
    type-aliases-package: com.watson.entity
mybatis-plus:
    mapper-locations: classpath*:/mapper/*.xml
    typeAliasesPackage: com.watson.entity
    global-config:
        banner: false
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
bocchi:
    path: D:\\WorkSpace\\AppCache\\